device: cuda
dataset:
  name: RSI-CB256
  dataset_dir: /media/joshuawen/Joshua_SSD3/Datasets/RGB/classification/RSI-CB256
  image_size: 256
  n_channels: 3
  n_classes: 35
model:
  type: custom
  name: resnet
  init_mode: kaiming_fan_out
  resnet:
    initial_channels: 64
    block_type: basic
    n_blocks: [3, 4, 6, 3]
train:
  resume: False
  seed: 0
  precision: O0
  batch_size: 256
  subdivision: 1
  optimizer: sgd
  base_lr: 0.1
  momentum: 0.9
  nesterov: True
  weight_decay: 1e-4
  output_dir: experiments/Google-China/resnet34/exp00
  log_period: 10
  checkpoint_period: 10
  use_tensorboard: True
  distributed: False
  dataloader:
    num_workers: 8
    drop_last: True
    pin_memory: True
validation:
  batch_size: 1024
  dataloader:
    num_workers: 8
    drop_last: False
    pin_memory: True
test:
  output_dir: /media/joshuawen/Joshua_SSD3/Exp/Classification/RSI-CB256/resnet34/exp00
  checkpoint: /media/joshuawen/Joshua_SSD3/Exp/Classification/RSI-CB256/resnet34/exp00/checkpoint_00120.pth
  batch_size: 4
scheduler:
  epochs: 90
  type: multistep
  milestones: [30, 60]
  lr_decay: 0.1
augmentation:
  use_random_crop: True
  use_random_horizontal_flip: True
  use_cutout: False
  use_random_erasing: False
  use_dual_cutout: False
  use_mixup: False
  use_ricap: False
  use_cutmix: False
  use_label_smoothing: False
tta:
  use_resize: True
  use_center_crop: True
  resize: 256
tensorboard:
  train_images: True
  val_images: True
  model_params: True
