device: cuda
dataset:
  name: Google-China
  dataset_dir: /media/joshuawen/Joshua_SSD3/Datasets/RGB/classification/Google-China
  image_size: 200
  n_channels: 3
  n_classes: 12
model:
  type: custom
  name: vgg
  init_mode: kaiming_fan_out
  vgg:
    n_channels: [64, 128, 256, 512, 512]
    n_layers: [2, 2, 3, 3, 3]
    use_bn: True
train:
  resume: False
  seed: 0
  precision: O0
  batch_size: 256
  subdivision: 8
  optimizer: sgd
  base_lr: 0.01
  momentum: 0.9
  nesterov: True
  weight_decay: 5e-4
  output_dir: /home/joshuawen/Downloads/Google-China/vgg16/exp08
  log_period: 10
  checkpoint_period: 10
  use_tensorboard: True
  distributed: False
  dataloader:
    num_workers: 8
    drop_last: True
    pin_memory: True
validation:
  batch_size: 256
  dataloader:
    num_workers: 8
    drop_last: False
    pin_memory: True
test:
  output_dir: /home/joshuawen/Downloads/Google-China/vgg16/exp08/checkpoint/
  checkpoint: /home/joshuawen/Downloads/Google-China/vgg16/exp08/checkpoint/checkpoint_00120.pth
  batch_size: 64
scheduler:
  epochs: 90
  type: multistep
  milestones: [30, 60]
  lr_decay: 0.1
augmentation:
  use_random_crop: True
  use_random_horizontal_flip: True
  use_cutout: False
  use_random_erasing: False
  use_dual_cutout: False
  use_mixup: False
  use_ricap: False
  use_cutmix: False
  use_label_smoothing: False
tta:
  use_resize: True
  use_center_crop: True
  resize: 256
tensorboard:
  train_images: True
  val_images: True
  model_params: True
